/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a OSBBInfoSrvAdaptor OSBBInfoSrv.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OSBBINFOSRVADAPTOR_H
#define OSBBINFOSRVADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.OSBBInfoSrv
 */
class OSBBInfoSrvAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.OSBBInfoSrv")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.OSBBInfoSrv\">\n"
"    <signal name=\"upTimeChanged\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"upTime\"/>\n"
"    </signal>\n"
"    <signal name=\"lastSyncDTChanged\">\n"
"      <arg direction=\"out\" type=\"((iii)(iiii)i)\" name=\"lastSyncDT\"/>\n"
"      <annotation value=\"QDateTime\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <method name=\"getUpTime\">\n"
"      <arg direction=\"out\" type=\"u\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    OSBBInfoSrvAdaptor(QObject *parent);
    virtual ~OSBBInfoSrvAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    uint getUpTime();
Q_SIGNALS: // SIGNALS
    void lastSyncDTChanged(const QDateTime &lastSyncDT);
    void upTimeChanged(uint upTime);
};

#endif
