/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a OSBBInfoSrvAdaptor OSBBInfoSrv.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "OSBBInfoSrvAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OSBBInfoSrvAdaptor
 */

OSBBInfoSrvAdaptor::OSBBInfoSrvAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OSBBInfoSrvAdaptor::~OSBBInfoSrvAdaptor()
{
    // destructor
}

uint OSBBInfoSrvAdaptor::getUpTime()
{
    // handle method call local.OSBBInfoSrv.getUpTime
    uint out0;
    QMetaObject::invokeMethod(parent(), "getUpTime", Q_RETURN_ARG(uint, out0));
    return out0;
}

double OSBBInfoSrvAdaptor::process()
{
    // handle method call local.OSBBInfoSrv.process
    double out0;
    QMetaObject::invokeMethod(parent(), "process", Q_RETURN_ARG(double, out0));
    return out0;
}

